# Generated by Django 4.2.3 on 2023-07-25 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='type',
            field=models.CharField(choices=[('HOME', 'Home'), ('WORK', 'Work')], default='HOME', max_length=256),
        ),
    ]
